version: "3.7"
networks:
  internal: {}
services:
  sut:
    build:
      context: .
      dockerfile: ./Dockerfile.sut
    profiles:
      - with-sut
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    networks:
      - internal
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/yates?connection_limit=30
      - DATABASE_URL_2=postgresql://postgres:postgres@db:5432/yates_2?connection_limit=30

  db:
    image: postgres:11
    volumes:
      - ./docker-init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: yates,yates_2
    ports:
      - 5432:5432
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
